<a href="https://colab.research.google.com/github/Aatka-Saleem/ML-Core-Implementations/blob/main/Data_Preprocessing_and_Feature_Engineering_Cleaning_Tabular_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## TABULAR DATA CLEANING EXERCISE

### Imports

In [ ]:
import pandas as pd

### Problem: The Movie Revenue Dataset

**Dataset Description**

This dataset has been obtained from https://www.the-numbers.com/movie/budgets

This data has already been saved in a csv file called 'Dataset_Movie_Revenue.csv' and provided with this notebook.

The csv file contains 6 columns (A to F) as follows:
- Column A: Rank or serial number of the movie as per the production budget. Movies are ranked in decreasing order of their respective production budgets.
- Column B: Release date of the movie.
- Column C: Title of the movie.
- Column D: Production budget of the movie in dollars.
- Column E: Domestic gross in dollars made by the movie.
- Column F: Worldwide gross in dollars made by the movie.

### Exploring the Dataset in Microsoft Excel
Open the file in Microsoft Excel and try identifying problems with data.

Observe the following:
- There is a total of 6169 entries in the dataset.
- Different columns have different datatypes. In Microsoft Excel, strings are right-aligned and numbers are left-aligned. Column B 'Release Date' is of 'date' type.
- In 'Release date' some entries are missing (see rows 793 and 1270); 'Unknown' is written instead. These are missing attribute values.
- Some values are 0 in Columns E and F. These movies could be the ones which were never released or may be the attribute values are missing.
- The heading of some columns have gaps in between the two words. This could create problem when reading these heading in Python as Python variable names do not allow spaces.
- The number given in columns D, E and F are comma-separated. This can create problem when reading these columns into Python as integers.

### Exploring the Dataset in Python
**Loading Data**

In [ ]:
#Reading the file into a dataframe using pandas method 'read_csv'
data=pd.read_csv('Dataset_Movie_Revenue.csv')
#Displaying the read contents
data
#Contains 6169 rows and 6 columns

,Rank,Release Date,Title,Production Budget,Domestic Gross,Worldwide Gross
0,1,23-Apr-19,Avengers: Endgame,"400,000,000","858,373,000","2,797,800,564"
1,2,20-May-11,Pirates of the Caribbean: On Stranger Tides,"379,000,000","241,071,802","1,045,713,802"
2,3,22-Apr-15,Avengers: Age of Ultron,"365,000,000","459,005,868","1,395,316,979"
3,4,16-Dec-15,Star Wars Ep. VII: The Force Awakens,"306,000,000","936,662,225","2,064,615,817"
4,5,25-Apr-18,Avengers: Infinity War,"300,000,000","678,815,482","2,044,540,523"
...,...,...,...,...,...,...
6164,6165,Unknown,Red 11,"7,000",0,0
6165,6166,02-Apr-99,Following,"6,000","48,482","240,495"
6166,6167,13-Jul-05,Return to the Land of Wonders,"5,000","1,338","1,338"
6167,6168,29-Sep-15,A Plague So Pleasant,"1,400",0,0
6168,6169,05-Aug-05,My Date With Drew,"1,100","181,041","181,041"

**Exploring Data**

In [ ]:
#Finding datatype of data
type(data)
#The data has been read as a dataframe

pandas.core.frame.DataFrame

In [ ]:
data.info()
#This information shows that each column has 6169 entries.
#Non of the columns contain any 'null' value, however we kmow that there are some unwanted values ('unknown' and 0) in some columns.
#Datatype of only first column is 'integer', and remaining are 'object' showing that these are read as strings.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6169 entries, 0 to 6168
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Rank               6169 non-null   int64
 1   Release Date       6169 non-null   object
 2   Title              6169 non-null   object
 3   Production Budget  6169 non-null   object
 4   Domestic Gross     6169 non-null   object
 5   Worldwide Gross    6169 non-null   object
dtypes: int64(1), object(5)
memory usage: 289.3+ KB

### Cleaning the Dataset
Suppose we want to use this data to predict the movie revenue.

Movie revenue is indicated by the 'Domestic Gross' (column E) and 'World Gross' (column F) values.

Let us select 'World Gross' as the target.

Now the only feature that actually seems to effect this revenue is 'Production Budget'.

So our hypothesis is to predict the 'World Gross' value from the corresponding 'Production Budget' value.

In **Microsft Excel** we can do the following:
- Save the file as 'Dataset_Movie_revenue_Clean_Excel.csv' (to save the original file from being altered).
- Remove all other irrelevent columns, i.e. remove coulumns A, B, C, and E.
- Change the titles of the remaining two columns to 'Production_Budget' and 'World_Gross' (remove spaces from names).
- Since both the columns should contain numbers, remove the commas from the values. To do this, select all the numbers, right click->Format Cells->Numbers->select 'Numbers' and unclick 'Use 1000 Separator'.
- Delete all rows where the data is missing, i.e. delete all the rows where 'World_Gross' is 0. To do this, sort the column on 'World_Gross'; all 0 entries will come on top; delete all these row.
- How many rows did u delete? Is this number significant as compared to the total dataset size?

All these steps can be done through Python programming as well. Try this.

Now keep this file for future use (will be used in upcoming notebooks).

In [ ]:
#lets explore the new clean file in python.
#run the following two methods and observe the information these methods provide.
clean_data_excel=pd.read_csv('Dataset_Movie_Revenue_Clean_Excel.csv')
print(clean_data_excel.info())
print(clean_data_excel.describe())
clean_data_excel

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6168 entries, 0 to 6167
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Production_Budget  5773 non-null   float64
 1   Worldwide_Gross    5773 non-null   float64
dtypes: float64(2)
memory usage: 96.5 KB
None
       Production_Budget  Worldwide_Gross
count       5.773000e+03     5.773000e+03
mean        3.301073e+07     9.713447e+07
std         4.226197e+07     1.834412e+08
min         1.100000e+03     1.700000e+01
25%         6.000000e+06     6.756412e+06
50%         1.800000e+07     3.210082e+07
75%         4.000000e+07     1.023328e+08
max         4.000000e+08     2.845900e+09

      Production_Budget  Worldwide_Gross
0           400000000.0     2.797801e+09
1           379000000.0     1.045714e+09
2           365000000.0     1.395317e+09
3           306000000.0     2.064616e+09
4           300000000.0     2.044541e+09
...                 ...              ...
6163                NaN              NaN
6164             6000.0     2.404950e+05
6165             5000.0     1.338000e+03
6166                NaN              NaN
6167             1100.0     1.810410e+05

[6168 rows x 2 columns]

Let us try all these cleaning steps using **Python**.

Save the file as 'Dataset_Movie_Revenue_Clean_Python.csv'.

In [ ]:
#Remove all other irrelevent columns, i.e. remove coulumns A, B, C, and E.
data=data.drop(['Rank','Release Date', 'Title', 'Domestic Gross'], axis=1)
data

     Production Budget Worldwide Gross
0          400,000,000   2,797,800,564
1          379,000,000   1,045,713,802
2          365,000,000   1,395,316,979
3          306,000,000   2,064,615,817
4          300,000,000   2,044,540,523
...                ...             ...
6164             7,000               0
6165             6,000         240,495
6166             5,000           1,338
6167             1,400               0
6168             1,100         181,041

[6169 rows x 2 columns]

In [ ]:
#Change the titles of the remaining two columns to 'Production_Budget' and 'World_Gross' (remove spaces from names).
data = data.rename(columns={'Production Budget':'Production_Budget', 'Worldwide Gross': 'World_Gross'})
data

     Production_Budget    World_Gross
0          400,000,000  2,797,800,564
1          379,000,000  1,045,713,802
2          365,000,000  1,395,316,979
3          306,000,000  2,064,615,817
4          300,000,000  2,044,540,523
...                ...            ...
6164             7,000              0
6165             6,000        240,495
6166             5,000          1,338
6167             1,400              0
6168             1,100        181,041

[6169 rows x 2 columns]

In [ ]:
#Since both the columns should contain numbers, remove the commas from the values.
data['Production_Budget'] = (data['Production_Budget'].astype(str).str.replace(',', ''))
data['Production_Budget'] = pd.to_numeric(data['Production_Budget'], errors='coerce')
data['World_Gross'] = (data['World_Gross'].astype(str).str.replace(',', ''))
data['World_Gross'] = pd.to_numeric(data['World_Gross'], errors='coerce')
print(data.info())
data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6169 entries, 0 to 6168
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Production_Budget  6169 non-null   int64
 1   World_Gross        6169 non-null   int64
dtypes: int64(2)
memory usage: 96.5 KB
None

      Production_Budget  World_Gross
0             400000000   2797800564
1             379000000   1045713802
2             365000000   1395316979
3             306000000   2064615817
4             300000000   2044540523
...                 ...          ...
6164               7000            0
6165               6000       240495
6166               5000         1338
6167               1400            0
6168               1100       181041

[6169 rows x 2 columns]

In [ ]:
#Delete all rows where the data is missing, i.e. delete all the rows where 'World_Gross' is 0.
data = data.drop(data[data['World_Gross'] == 0].index)
data

      Production_Budget  World_Gross
0             400000000   2797800564
1             379000000   1045713802
2             365000000   1395316979
3             306000000   2064615817
4             300000000   2044540523
...                 ...          ...
6162               7000        71644
6163               7000          900
6165               6000       240495
6166               5000         1338
6168               1100       181041

[5773 rows x 2 columns]

In [ ]:
#How many rows did u delete? Is this number significant as compared to the total dataset size?
print(6169-len(data))
# Since this is a very small percentage of teh total dataset, it is not significant.

396

In [ ]:
#All the changes that we have made so far are done on the dataframe, and not in the original csv file.
#The to_csv method can be used to save the dataframe into a csv file.
#Lets save this clean data into a new file 'D1_Movie_Revenue_Dataset_Clean_Python.csv'
data.to_csv('Dataset_Movie_Revenue_Clean_Python.csv', index=False)

In [ ]:
#Lets read and explore the new clean file in python.
clean_data_python=pd.read_csv('Dataset_Movie_Revenue_Clean_Python.csv')

#Run the following two methods and observe the information these methods provide.
print(clean_data_python.info())
print(clean_data_python.describe())
clean_data_python

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5773 entries, 0 to 5772
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Production_Budget  5773 non-null   int64
 1   World_Gross        5773 non-null   int64
dtypes: int64(2)
memory usage: 90.3 KB
None
       Production_Budget   World_Gross
count       5.773000e+03  5.773000e+03
mean        3.301073e+07  9.713447e+07
std         4.226197e+07  1.834412e+08
min         1.100000e+03  1.700000e+01
25%         6.000000e+06  6.756412e+06
50%         1.800000e+07  3.210082e+07
75%         4.000000e+07  1.023328e+08
max         4.000000e+08  2.845900e+09

      Production_Budget  World_Gross
0             400000000   2797800564
1             379000000   1045713802
2             365000000   1395316979
3             306000000   2064615817
4             300000000   2044540523
...                 ...          ...
5768               7000        71644
5769               7000          900
5770               6000       240495
5771               5000         1338
5772               1100       181041

[5773 rows x 2 columns]

### Task for you

Repeat the cleaning process in Python,
this time instead of deleting the '0' columns, replace the zeros with average value of the column.

Tryout Pandas DataFrame’s fillna() method.

In [ ]:
import pandas as pd
import numpy as np

# Re-reading the original file to start fresh for the new cleaning process
data_new_clean = pd.read_csv('Dataset_Movie_Revenue.csv')
display(data_new_clean.head())

,Rank,Release Date,Title,Production Budget,Domestic Gross,Worldwide Gross
0,1,23-Apr-19,Avengers: Endgame,"400,000,000","858,373,000","2,797,800,564"
1,2,20-May-11,Pirates of the Caribbean: On Stranger Tides,"379,000,000","241,071,802","1,045,713,802"
2,3,22-Apr-15,Avengers: Age of Ultron,"365,000,000","459,005,868","1,395,316,979"
3,4,16-Dec-15,Star Wars Ep. VII: The Force Awakens,"306,000,000","936,662,225","2,064,615,817"
4,5,25-Apr-18,Avengers: Infinity War,"300,000,000","678,815,482","2,044,540,523"

In [ ]:
# Remove all other irrelevant columns
data_new_clean = data_new_clean.drop(['Rank','Release Date', 'Title', 'Domestic Gross'], axis=1)

# Change the titles of the remaining two columns
data_new_clean = data_new_clean.rename(columns={'Production Budget':'Production_Budget', 'Worldwide Gross': 'World_Gross'})
display(data_new_clean.head())

  Production_Budget    World_Gross
0       400,000,000  2,797,800,564
1       379,000,000  1,045,713,802
2       365,000,000  1,395,316,979
3       306,000,000  2,064,615,817
4       300,000,000  2,044,540,523

In [ ]:
# Remove commas from the values and convert to numeric
data_new_clean['Production_Budget'] = (data_new_clean['Production_Budget'].astype(str).str.replace(',', ''))
data_new_clean['Production_Budget'] = pd.to_numeric(data_new_clean['Production_Budget'], errors='coerce')

data_new_clean['World_Gross'] = (data_new_clean['World_Gross'].astype(str).str.replace(',', ''))
data_new_clean['World_Gross'] = pd.to_numeric(data_new_clean['World_Gross'], errors='coerce')

print("DataFrame Info after numeric conversion:")
data_new_clean.info()
display(data_new_clean.head())

DataFrame Info after numeric conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6169 entries, 0 to 6168
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Production_Budget  6169 non-null   int64
 1   World_Gross        6169 non-null   int64
dtypes: int64(2)
memory usage: 96.5 KB

   Production_Budget  World_Gross
0          400000000   2797800564
1          379000000   1045713802
2          365000000   1395316979
3          306000000   2064615817
4          300000000   2044540523

In [ ]:
# Replace '0' values in 'World_Gross' with NaN first
data_new_clean['World_Gross'] = data_new_clean['World_Gross'].replace(0, np.nan)

# Fill the NaN values with the calculated mean
data_new_clean['World_Gross'] = data_new_clean['World_Gross'].fillna(data_new_clean['World_Gross'].mean())

print("\nDataFrame Info after filling 0s with mean:")
data_new_clean.info()
display(data_new_clean)

DataFrame Info after filling 0s with mean:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6169 entries, 0 to 6168
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Production_Budget  6169 non-null   int64
 1   World_Gross        6169 non-null   float64
dtypes: float64(1), int64(1)
memory usage: 96.5 KB

      Production_Budget   World_Gross
0             400000000  2.797801e+09
1             379000000  1.045714e+09
2             365000000  1.395317e+09
3             306000000  2.064616e+09
4             300000000  2.044541e+09
...                 ...           ...
6164               7000  9.713447e+07
6165               6000  2.404950e+05
6166               5000  1.338000e+03
6167               1400  9.713447e+07
6168               1100  1.810410e+05

[6169 rows x 2 columns]

In [ ]:
# Save this cleaned data into a new file 'Dataset_Movie_Revenue_Clean_Python_Mean_Fill.csv'
data_new_clean.to_csv('Dataset_Movie_Revenue_Clean_Python_Mean_Fill.csv', index=False)

print("Cleaned data saved to 'Dataset_Movie_Revenue_Clean_Python_Mean_Fill.csv'")

Cleaned data saved to 'Dataset_Movie_Revenue_Clean_Python_Mean_Fill.csv'