<a href="https://colab.research.google.com/github/Aatka-Saleem/ML-Core-Implementations/blob/main/01-Data-Foundations/Data_Preprocessing_and_Feature_Engineering_Categorical_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## CATEGORICAL DATA EXERCISE

### Imports

In [ ]:
import pandas as pd

### Problem: The Heart Dataset

**Dataset Description**

File name: 'Dataset_Heart1.csv'

This dataset has been obtained from Kaggle: https://www.kaggle.com/fedesoriano/heart-failure-prediction

The data contains 918 observations with 12 attributes as described below:
1. Age: patient's age, range: 28 to 77.
2. Sex: patient's gender, M(79%), F(21%).
3. ChestPainType: ASY (54%), NAP (22%), Other(24%).
4. RestingBP: resting blood pressure, range: 0 to 200.
5. Cholestrol: serum cholestrol, range: 0 to 603.
6. FastingBS: fasting blood sugar, 0 or 1.
7. RestingECG: resting electrocardiogram results, Normal (60%), LVH (20%), Other (19%).
8. MaxHR: maximum heart rate achieved, range: 60 to 202.
9. ExerciseAngina: exercise induced angina, true(317-40%), false (547-60%).
10. OldPeak: old peak=ST, range: -2.6 to 6.2.
11. ST_Slope: ST slope, Up or flat.
12. HeartDisease: target, 1 or 0.

Last column indicates presence of heart disease given the remaining 11 attributes.

This is a binary classification problem.

Contains categorical data, otherwise the dataset is clean.

**Loading Data**

In [ ]:
#Reading the file into a dataframe
data=pd.read_csv('Dataset_Heart1.csv')
#Displaying the read contents
data

,Age,Gender,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

**Exploring Data**

In [ ]:
#Finding datatype of data
type(data)

pandas.core.frame.DataFrame

In [ ]:
data.info()
#This information shows that each column has 918 entries.
#Non of the columns contain any 'null' value.
#There are 5 attributes with datatype of 'object'/'string'.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Gender          918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

### Encoding Categorical Data

Consider the 'ExerciseAngina' column first and apply **dummy variable encoding**.
- This is a binary variable as its presence counts towards increased risk of heart disease and absence means otherwise.
- Can be ecoded using dummy variable encoding.

In [ ]:
#The following method is used to count the possible values in a column
data['ExerciseAngina'].value_counts()
#This shows that there are two possible values for this attribute: 'Y' or 'N'.
#Also there are 547 entries for 'N' and 371 entries for 'Y'.

ExerciseAngina
N    547
Y    371
Name: count, dtype: int64

In [ ]:
#The simplest way to encode 'ExerciseAngina' as dummy varaible is to use the replace method.
data['ExerciseAngina'] = data['ExerciseAngina'].replace({'N': 0, 'Y': 1})
data
#Observe that values of the column 'ExerciseAngina' have been cahnged to 0 and 1.

/tmp/ipython-input-1544208082.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['ExerciseAngina'] = data['ExerciseAngina'].replace({'N': 0, 'Y': 1})

,Age,Gender,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,0,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,0,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,0,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,1,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,0,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,0,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,0,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,1,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,0,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,0,0.0,Up,0

Now consider the 'ChestPainType' column and apply **ordinal encoding**.

In [ ]:
data['ChestPainType'].value_counts()
#This column contains 4 different values ASY, NAP, ATA, TA

ChestPainType
ASY    496
NAP    203
ATA    173
TA      46
Name: count, dtype: int64

Let us use Ordinal encoding as follows:
- TA (typical angina): 0
- ATA (atypical angina): 1
- NAP (non-anginal pain): 2
- ASY (asymptomatic): 3

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder = OrdinalEncoder(categories=[['TA', 'ATA', 'NAP', 'ASY']])
#categories specify the order of numbering, numbering always starts from 0

data['ChestPainType'] = ordinal_encoder.fit_transform(data[['ChestPainType']])

# Alternatively
#data['ChestPainType']=data['ChestPainType'].replace({'TA':0, 'ATA':1, 'NAP':2, 'ASY':3})

data

,Age,Gender,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,1.0,140,289,0,Normal,172,0,0.0,Up,0
1,49,F,2.0,160,180,0,Normal,156,0,1.0,Flat,1
2,37,M,1.0,130,283,0,ST,98,0,0.0,Up,0
3,48,F,3.0,138,214,0,Normal,108,1,1.5,Flat,1
4,54,M,2.0,150,195,0,Normal,122,0,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,0.0,110,264,0,Normal,132,0,1.2,Flat,1
914,68,M,3.0,144,193,1,Normal,141,0,3.4,Flat,1
915,57,M,3.0,130,131,0,Normal,115,1,1.2,Flat,1
916,57,F,1.0,130,236,0,LVH,174,0,0.0,Flat,1
917,38,M,2.0,138,175,0,Normal,173,0,0.0,Up,0

Now consider the 'RestingECG' column and apply **one-hot encoding**.

In [ ]:
data['RestingECG'].value_counts()

RestingECG
Normal    552
LVH       188
ST        178
Name: count, dtype: int64

In [ ]:
# #one hot encodig simple
# df = pd.get_dummies(data, columns=['RestingECG'], prefix='ECG', dtype=int)
# df

In [ ]:
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder = OneHotEncoder()
restingECG_encoded = one_hot_encoder.fit_transform(data[['RestingECG']]).toarray()
#fit_transform returns a sparse matrix which need to ne converted to array using the toarray method
restingECG_encoded

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [ ]:
#Now converting restingECG_encoded to DataFrame
restingECG_encoded_dataframe = pd.DataFrame(restingECG_encoded,columns=one_hot_encoder.get_feature_names_out())
restingECG_encoded_dataframe

     RestingECG_LVH  RestingECG_Normal  RestingECG_ST
0               0.0                1.0            0.0
1               0.0                1.0            0.0
2               0.0                0.0            1.0
3               0.0                1.0            0.0
4               0.0                1.0            0.0
..              ...                ...            ...
913             0.0                1.0            0.0
914             0.0                1.0            0.0
915             0.0                1.0            0.0
916             1.0                0.0            0.0
917             0.0                1.0            0.0

[918 rows x 3 columns]

In [ ]:
#Replacing the original RestingECG column with these one-hot encoded columns
data=data.drop(['RestingECG'],axis=1)
data = pd.concat([data, restingECG_encoded_dataframe], axis=1)
data
#Note how three new columns with appropriate names have been added

,Age,Gender,ChestPainType,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,RestingECG_LVH,RestingECG_Normal,RestingECG_ST
0,40,M,1.0,140,289,0,172,0,0.0,Up,0,0.0,1.0,0.0
1,49,F,2.0,160,180,0,156,0,1.0,Flat,1,0.0,1.0,0.0
2,37,M,1.0,130,283,0,98,0,0.0,Up,0,0.0,0.0,1.0
3,48,F,3.0,138,214,0,108,1,1.5,Flat,1,0.0,1.0,0.0
4,54,M,2.0,150,195,0,122,0,0.0,Up,0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,0.0,110,264,0,132,0,1.2,Flat,1,0.0,1.0,0.0
914,68,M,3.0,144,193,1,141,0,3.4,Flat,1,0.0,1.0,0.0
915,57,M,3.0,130,131,0,115,1,1.2,Flat,1,0.0,1.0,0.0
916,57,F,1.0,130,236,0,174,0,0.0,Flat,1,1.0,0.0,0.0
917,38,M,2.0,138,175,0,173,0,0.0,Up,0,0.0,1.0,0.0

In [ ]:
#All the changes that we have made so far are done on the dataframe, and not in the original csv file.
#The to_csv method can be used to save the dataframe into a csv file.
data.to_csv('Dataset_Heart1_Clean.csv')

### Task for you

Try different types of encoding on the remaining categorical features.

In [ ]:
data['Gender'].value_counts()

Gender
M    725
F    193
Name: count, dtype: int64

In [ ]:
data['Gender'] = data['Gender'].replace({'M': 0, 'F': 1})
data

/tmp/ipython-input-1442273394.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['Gender'] = data['Gender'].replace({'M': 0, 'F': 1})

,Age,Gender,ChestPainType,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,RestingECG_LVH,RestingECG_Normal,RestingECG_ST
0,40,0,1.0,140,289,0,172,0,0.0,Up,0,0.0,1.0,0.0
1,49,1,2.0,160,180,0,156,0,1.0,Flat,1,0.0,1.0,0.0
2,37,0,1.0,130,283,0,98,0,0.0,Up,0,0.0,0.0,1.0
3,48,1,3.0,138,214,0,108,1,1.5,Flat,1,0.0,1.0,0.0
4,54,0,2.0,150,195,0,122,0,0.0,Up,0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,0,0.0,110,264,0,132,0,1.2,Flat,1,0.0,1.0,0.0
914,68,0,3.0,144,193,1,141,0,3.4,Flat,1,0.0,1.0,0.0
915,57,0,3.0,130,131,0,115,1,1.2,Flat,1,0.0,1.0,0.0
916,57,1,1.0,130,236,0,174,0,0.0,Flat,1,1.0,0.0,0.0
917,38,0,2.0,138,175,0,173,0,0.0,Up,0,0.0,1.0,0.0

In [ ]:
data['ST_Slope'].value_counts()

ST_Slope
Flat    460
Up      395
Down     63
Name: count, dtype: int64

In [ ]:
data['ST_Slope'] = data['ST_Slope'].replace({'Flat': 0, 'Up': 1, 'Down': 2})
data

,Age,Gender,ChestPainType,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,RestingECG_LVH,RestingECG_Normal,RestingECG_ST
0,40,0,1.0,140,289,0,172,0,0.0,1.0,0,0.0,1.0,0.0
1,49,1,2.0,160,180,0,156,0,1.0,0.0,1,0.0,1.0,0.0
2,37,0,1.0,130,283,0,98,0,0.0,1.0,0,0.0,0.0,1.0
3,48,1,3.0,138,214,0,108,1,1.5,0.0,1,0.0,1.0,0.0
4,54,0,2.0,150,195,0,122,0,0.0,1.0,0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,0,0.0,110,264,0,132,0,1.2,0.0,1,0.0,1.0,0.0
914,68,0,3.0,144,193,1,141,0,3.4,0.0,1,0.0,1.0,0.0
915,57,0,3.0,130,131,0,115,1,1.2,0.0,1,0.0,1.0,0.0
916,57,1,1.0,130,236,0,174,0,0.0,0.0,1,1.0,0.0,0.0
917,38,0,2.0,138,175,0,173,0,0.0,1.0,0,0.0,1.0,0.0